# Generated by Django 5.1.1 on 2024-11-04 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(default='email@email.com', max_length=127)),
                ('adress', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('is_validated', models.BooleanField(default=False)),
                ('study_domain', models.CharField(choices=[('science', 'Sciences'), ('literature', 'Littérature'), ('engineering', 'Ingénierie'), ('arts', 'Arts'), ('business', 'Affaires'), ('medicine', 'Médecine')], default='science', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('study_domain', models.CharField(choices=[('science', 'Sciences'), ('literature', 'Littérature'), ('engineering', 'Ingénierie'), ('arts', 'Arts'), ('business', 'Affaires'), ('medicine', 'Médecine')], default='science', max_length=50)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parcoursup.etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('firstname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=127, unique=True)),
                ('study_domain', models.CharField(choices=[('science', 'Sciences'), ('literature', 'Littérature'), ('engineering', 'Ingénierie'), ('arts', 'Arts'), ('business', 'Affaires'), ('medicine', 'Médecine')], default='science', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée')], max_length=50)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parcoursup.offer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parcoursup.student')),
            ],
        ),
    ]
