# Generated by Django 5.1.1 on 2024-11-05 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Étudiant'), ('etablissement', 'Établissement')], max_length=20)),
                ('firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('adress', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('study_domain', models.CharField(choices=[('science', 'Sciences'), ('literature', 'Littérature'), ('engineering', 'Ingénierie'), ('arts', 'Arts'), ('business', 'Affaires'), ('medicine', 'Médecine')], default='science', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('study_domain', models.CharField(choices=[('science', 'Sciences'), ('literature', 'Littérature'), ('engineering', 'Ingénierie'), ('arts', 'Arts'), ('business', 'Affaires'), ('medicine', 'Médecine')], default='science', max_length=50)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parcoursup.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée')], max_length=50)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parcoursup.offer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parcoursup.userprofile')),
            ],
        ),
    ]
