# Generated by Django 5.1.1 on 2024-10-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parcoursup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=127),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image_url',
            field=models.URLField(max_length=3000),
        ),
    ]
