# Generated by Django 5.1.1 on 2024-11-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parcoursup', '0002_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image_url',
            field=models.URLField(max_length=50000),
        ),
    ]
