# Generated by Django 5.1.1 on 2024-10-14 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parcoursup', '0002_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parcoursup.etablissement')),
            ],
        ),
    ]
