# Generated by Django 5.1.1 on 2024-10-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parcoursup', '0002_alter_etablissement_email_alter_offer_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image_url',
            field=models.URLField(max_length=10000),
        ),
    ]
