# Generated by Django 5.1.1 on 2024-11-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parcoursup', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissement',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
