# Generated by Django 5.1.1 on 2024-10-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parcoursup', '0003_offerpro'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='firstname',
            field=models.CharField(default='prenom', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='study_domain',
            field=models.CharField(choices=[('science', 'Science'), ('literature', 'Literature'), ('engineering', 'Engineering'), ('arts', 'Arts'), ('business', 'Business'), ('medicine', 'Medicine')], default='science', max_length=50),
        ),
    ]
