# Generated by Django 5.1.1 on 2024-10-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parcoursup', '0005_alter_offer_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='offer',
            name='study_domain',
            field=models.CharField(choices=[('science', 'Science'), ('literature', 'Literature'), ('engineering', 'Engineering'), ('arts', 'Arts'), ('business', 'Business'), ('medicine', 'Medicine')], default='science', max_length=50),
        ),
    ]
