# Generated by Django 5.1.1 on 2024-10-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parcoursup', '0006_remove_offer_category_remove_offer_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='adress',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='study_domain',
            field=models.CharField(choices=[('science', 'Sciences'), ('literature', 'Littérature'), ('engineering', 'Ingénierie'), ('arts', 'Arts'), ('business', 'Affaires'), ('medicine', 'Médecine')], default='science', max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='study_domain',
            field=models.CharField(choices=[('science', 'Sciences'), ('literature', 'Littérature'), ('engineering', 'Ingénierie'), ('arts', 'Arts'), ('business', 'Affaires'), ('medicine', 'Médecine')], default='science', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_domain',
            field=models.CharField(choices=[('science', 'Sciences'), ('literature', 'Littérature'), ('engineering', 'Ingénierie'), ('arts', 'Arts'), ('business', 'Affaires'), ('medicine', 'Médecine')], default='science', max_length=50),
        ),
    ]
