# Generated by Django 5.1.1 on 2024-10-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parcoursup', '0009_remove_program_etablissement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image_url',
            field=models.URLField(max_length=2000),
        ),
    ]
