# Generated by Django 5.1.1 on 2024-10-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parcoursup', '0010_alter_offer_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissement',
            name='email',
        ),
    ]
